### ISSUE TITLE
Scope issue

### ISSUE THREAD

**Issue by 47ronin** [gevgeny/ui-highcharts#3]
Moving the chart data inside a function (or scope) breaks ui-highcharts so I have to leave it as the outermost declarations. Ideally, to pull in dynamic data, $scope.data and $scope.options should go inside the same loop as $http.jsonp() but it doesn't work. Please see example based on your demo chart:
http://jsfiddle.net/47ronin/zpfs9z6h/7/
![screen shot 2015-06-24 at 16 31 36](https://cloud.githubusercontent.com/assets/1022538/8343829/976db7b8-1a8e-11e5-9842-b143c08b7601.png)

**Comment by gevgeny** [comment]
I don't understand what you expect when you are trying to use data synchronously when it loads asynchronously. Anyway here is fixed example which works with async data and uses `ng-if` to postpone ui-highcharts init 
http://jsfiddle.net/rtyw81zw/2/

**Comment by 47ronin** [comment]
Thanks. I realize that I'm a newbie and the high-level task of just pulling in external JSON data, storing it, and assigning it gets more complicated when it comes to syncs —something I've only been studying through trial and error. I really appreciate the help. I'm going to have to take a formal study before I continue ;)

**Comment by gevgeny** [comment]
No problem :)
